java.lang.IllegalStateException: ..... does not have a NavController set   Javítva
Hiba oka:
mainActivity.xml
<fragment
            android:name="androidx.navigation.fragment.NavHostFragment"
ilyen hibánál átkell állítani a nevet erre
            />